from __future__ import annotations

import argparse
import os
from pathlib import Path

from common import (
    LifecyclePolicy,
    ManagedScope,
    ManifestError,
    SourceFetchError,
    emit_output,
    fetch_source_bytes,
    load_normalized_manifest,
    log_error,
    log_info,
    read_file_bytes,
    target_abspath,
    write_file_bytes,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Verify or sync files from a normalized manifest.")
    parser.add_argument("--mode", choices=("verify", "sync"), required=True)
    parser.add_argument(
        "--normalized-manifest-path",
        required=True,
        help="Path to the normalized manifest produced by validate_manifest.py.",
    )
    parser.add_argument(
        "--repo-root",
        required=True,
        help="Absolute path to the checked-out caller repository.",
    )
    return parser.parse_args()


def ensure_target_is_file(target_path: Path, target_label: str, entry_description: str) -> None:
    if target_path.exists() and not target_path.is_file():
        raise ManifestError(
            f"{entry_description} points to target_path '{target_label}', but that path exists and is not a regular file."
        )


def verify_entries(repo_root: Path, normalized_manifest_path: Path, source_token: str | None) -> None:
    entries = load_normalized_manifest(normalized_manifest_path)

    for entry in entries:
        log_info(f"Verifying {entry.describe()}.")
        if entry.managed_scope is not ManagedScope.WHOLE_FILE:
            raise ManifestError(
                f"{entry.describe()} is recognized by the manifest schema but not yet supported in execution for v1."
            )

        target_path = target_abspath(repo_root, entry.target_path)
        ensure_target_is_file(target_path, entry.target_path, entry.describe())

        if entry.lifecycle_policy is LifecyclePolicy.DISABLED:
            log_info(f"Skipping {entry.describe()} because lifecycle_policy is disabled.")
            continue

        if entry.lifecycle_policy is LifecyclePolicy.SEED_ONCE:
            if not target_path.is_file():
                raise ManifestError(
                    f"{entry.describe()} is missing required seed_once target '{entry.target_path}'."
                )
            log_info(f"Verified seed_once target exists for {entry.describe()}.")
            continue

        source_bytes = fetch_source_bytes(entry, source_token)
        if not target_path.is_file():
            raise ManifestError(
                f"{entry.describe()} is missing enforced target '{entry.target_path}'."
            )

        target_bytes = read_file_bytes(target_path)
        if target_bytes != source_bytes:
            raise ManifestError(
                f"{entry.describe()} is out of sync with its canonical source. Merge the sync PR created by this workflow."
            )

        log_info(f"Verified target is in sync for {entry.describe()}.")


def build_pr_body(changed_entries: list) -> str:
    lines = [
        "Automated sync of manifest-managed files.",
        "",
        "Changed files:",
    ]
    lines.extend(
        f"- `{entry.target_path}` <- `{entry.source_repo}@{entry.source_ref}:{entry.source_path}`"
        for entry in changed_entries
    )
    lines.extend(
        [
            "",
            "This PR was generated by `.github/workflows/sync-files-from-manifest.yml`.",
        ]
    )
    return "\n".join(lines)


def sync_entries(repo_root: Path, normalized_manifest_path: Path, source_token: str | None) -> None:
    entries = load_normalized_manifest(normalized_manifest_path)
    changed_entries = []
    changed_paths: list[str] = []

    for entry in entries:
        log_info(f"Synchronizing {entry.describe()}.")
        if entry.managed_scope is not ManagedScope.WHOLE_FILE:
            raise ManifestError(
                f"{entry.describe()} is recognized by the manifest schema but not yet supported in execution for v1."
            )

        target_path = target_abspath(repo_root, entry.target_path)
        ensure_target_is_file(target_path, entry.target_path, entry.describe())

        if entry.lifecycle_policy is LifecyclePolicy.DISABLED:
            log_info(f"Skipping {entry.describe()} because lifecycle_policy is disabled.")
            continue

        if entry.lifecycle_policy is LifecyclePolicy.SEED_ONCE and target_path.is_file():
            log_info(f"Leaving existing seed_once target unchanged for {entry.describe()}.")
            continue

        source_bytes = fetch_source_bytes(entry, source_token)
        current_bytes = read_file_bytes(target_path) if target_path.is_file() else None

        if current_bytes == source_bytes:
            log_info(f"Target already matches canonical source for {entry.describe()}.")
            continue

        write_file_bytes(target_path, source_bytes)
        changed_entries.append(entry)
        changed_paths.append(entry.target_path)
        log_info(f"Updated target '{entry.target_path}' for {entry.describe()}.")

    emit_output("changed", "true" if changed_paths else "false")
    emit_output("changed_count", str(len(changed_paths)))
    emit_output("changed_paths", "\n".join(changed_paths))
    emit_output(
        "pull_request_body",
        build_pr_body(changed_entries) if changed_entries else "Automated sync found no file changes.",
    )


def main() -> int:
    args = parse_args()
    repo_root = Path(args.repo_root).resolve()
    normalized_manifest_path = Path(args.normalized_manifest_path).resolve()
    source_token = os.getenv("SOURCE_TOKEN") or None

    if args.mode == "verify":
        verify_entries(repo_root, normalized_manifest_path, source_token)
    else:
        sync_entries(repo_root, normalized_manifest_path, source_token)

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (ManifestError, SourceFetchError) as exc:
        log_error(str(exc))
        raise SystemExit(1) from exc
    except Exception as exc:  # pragma: no cover - defensive guard for workflow logs
        log_error(f"Unexpected sync execution failure: {exc}")
        raise SystemExit(1) from exc
